name: Postgres Restore from Backup
description: Restore from a Postgres Backup
author: tj-actions
inputs:
  database_url:
    description: 'Database URL'
    required: true
  backup_file:
    description: 'Backup file name'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        psql -d "${{ inputs.database_url }}" < "${{ inputs.backup_file }}"
      shell: bash
branding:
  icon: hard-drive
  color: green
