name: Postgres Backup Restore
description: Manage a Postgres Backups and Restore
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  database_url:
    description: 'Database URL'
    required: true
  backup_file:
    description: 'Backup file name'
    required: true
  restore_pre_args:
    description: 'Pre argument'
    required: true
    default: '-Fc -j 8'

runs:
  using: 'composite'
  steps:
    - run: pg_restore "${{ inputs.restore_pre_args }}" -d "${{ inputs.database_url }}" "${{ inputs.backup_file }}"
      shell: bash
branding:
  icon: hard-drive
  color: green
