name: Postgres Backup Restore
description: Manage a Postgres Backups and Restore
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  database_url:
    description: 'Database URL'
    required: true
  backup_file:
    description: 'Backup file name'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/main.sh'
  post-entrypoint: '/cleanup.sh'
  post-if: 'success()'
branding:
  icon: hard-drive
  color: green
