name: Postgres Backup Restore
description: Manage a Postgres Backups and Restore
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  database_url:
    description: 'Database URL'
    required: true
  backup_file:
    description: 'Backup file name'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        psql -d "${{ inputs.database_url }}" "${{ inputs.backup_file }}"
      shell: bash
branding:
  icon: hard-drive
  color: green
