name: Postgres Restore from SQL Backup
description: Restore from a Postgres Backup
author: tj-actions
inputs:
  database_url:
    description: 'Database URL'
    required: true
  backup_file:
    description: 'Backup file name'
    required: true
  options:
    description: 'Extra options to pass directly to psql'
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        psql ${{ inputs.options }} -d "${{ inputs.database_url }}" < "${{ inputs.backup_file }}"
      shell: bash
branding:
  icon: hard-drive
  color: white
